exports.TERRA_SYMBOLS = {
    uusd: { name: 'TerraUSD Classic', symbol: 'USTC' },
    uluna:{ name: 'Luna Classic', symbol: 'LUNC' },
    uaud: { name: 'Terra Australian Dollar', symbol: 'AUTC' },
    ucad: { name: 'Terra Canadian Dollar', symbol: 'CATC' },
    uchf: { name: 'Terra Swiss Franc', symbol: 'CHTC' },
    ucny: { name: 'Terra Chinese Yuan', symbol: 'CNTC' },
    udkk: { name: 'Terra Danish Krone', symbol: 'DKKC' },
    ueur: { name: 'Terra Euro', symbol: 'EURC' },
    ugbp: { name: 'Terra British Pound', symbol: 'GBTC' },
    uhkd: { name: 'Terra HongKong Dollar', symbol: 'HKTC' },
    uinr: { name: 'Terra Indian Rupee', symbol: 'INTC' },
    ujpy: { name: 'Terra Japanese Yen', symbol: 'JPTC' },
    ukrw: { name: 'Terra South Korean Won', symbol: 'KRTC'},
    umnt: {name: 'Terra Mongolian Togrog', symbol: 'MNTC'},
    unok: { name: 'Terra Norwegian Krone', symbol: 'NOT' },
    usdr: {name: 'TerraSDR', symbol: 'SDTC'},
    usek: { name: 'Terra Swedish Krona', symbol: 'SETC' },
    usgd: { name: 'Terra Singapore Dolalr', symbol: 'SGTC' },
    uthb: { name: 'Terra Thai Baht', symbol: 'THTC' },
  };